### ISSUE TITLE
Gateway

### ISSUE THREAD

**Issue by Olivier4477** [rshtishi/payroll#1]
Hello,

I am Olivier4477 from stackoverflow, we discussed following my questions how to secure a microservice spring application.

why you use:

`<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>
while it is in maintenance and therefore will not evolve?

why you don't use:
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

thank you

**Comment by rshtishi** [comment]
Hi Olivier4477,

We have multiple options on what to use for creating the gateway server. (NGINX, ZUUL and Spring Cloud Gateway) 
I have chosen Zuul because:
* I have more experience with Zuul 
* Zuul is part of Netflix projects like our service discovery(Eureka)  and they are easier to integrate
* Zuul has pre-built routing service which he can use without the need to set up a routing service

**Comment by Olivier4477** [comment]
Ok me too I started with french tutorials on microservices that zuul used. Then I discovered that zuul is in maintenance at spring

As I understood, gateway included the zuul (or an equivalent). Developer level this does not change much (I put my project on hold because I have work to do with my training)

**Comment by rshtishi** [comment]
OK
